In [3]:
#question four
import numpy as np #(importing the library used to make the matrix into array form)
# constructing the given matrix.
matrix=np.array ([[1, 0.2, 0.5],
                [0.2, 1, 0.8],
                [0.5, 0.8, 1]])
# computing the inversion.
inverse= np.linalg.inv(matrix) # linalg stands for linear algebra, which contains the function of inv(inverse)
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [5]:
#(b) computing the determinant of the matrix 
import numpy as np
matrix=np.array ([[1, 0.2, 0.5],  # we first restate the given matrix
                [0.2, 1, 0.8],
                [0.5, 0.8, 1]])

determinant=np.linalg.det(matrix)#( since we are dealing with linear algebra and want to use the determinant fucntion, we use np.linalg)
print(determinant)

0.2299999999999999


In [6]:
#(c)Decomposing the matrix using eigen values and eigenvectors since the given matrix is a square matrix
#Eigenvectors are non-zero vectors associated with eigenvalues.
#Eigenvalues are scalars associated with a square matrix
import numpy as np

# state/define the matrix
matrix = np.array([ [1, 0.2, 0.5],
                    [0.2, 1, 0.8],
                    [0.5, 0.8, 1]])
                          

# Compute eigenvalues and eigenvectors using linalg
eigenvalues, eigenvectors = np.linalg.eig(matrix)


print(eigenvalues)


print(eigenvectors)


Eigenvalues:
[2.04100779 0.82188052 0.13711169]

Eigenvectors:
[[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]


In [7]:
#d)matrix transformation
import numpy as np

# Define the matrix

matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

# assuming a scalar
scalar = 2

# Perform the transformation (multiply matrix by the scalar)
transformed_matrix = scalar * matrix
# printing both matrices to compare the difference between the original and the transformed matrix.

print("Original Matrix:")
print(matrix)

print("\nTransformed Matrix (Scaled by 2):")
print(transformed_matrix)



Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Transformed Matrix (Scaled by 2):
[[2.  0.4 1. ]
 [0.4 2.  1.6]
 [1.  1.6 2. ]]


In [13]:
#question 5
#a python program to solve three linear equations using matrices.
#assuming a  matrix
"""2x + 3y - z = 8
  3x + y + 2z= 10
  -x +y + 2z = 3"""

import numpy as np

def solve_linear_equations(coefficients, constants):# defining the fuction
    solution = np.linalg.solve(coefficients, constants) # Condition for usage of linalg
    return solution


# Coefficients matrix
coefficients = np.array([[2, 3, -1],  # giving the fuction parameters/values to use.
                         [3, 1, 2],
                         [-1, 1, 2]])

# Constants matrix
constants = np.array([8, 10, 3])

# Solve the system of equations
result = solve_linear_equations(coefficients, constants)
print("Solution (x, y, z) in order =:", result)

#END
#TESTING RESUABILITY WITH OTHER VALUES.

coefficients = np.array([[1, 7, -3],
                         [5, 7, 2],
                         [3, 9, 2]])
constants = np.array([8, 10, 3])
result = solve_linear_equations(coefficients, constants)
print("Solution (x, y, z) in order =:", result)




Solution (x, y, z) in order =: [1.75       1.96428571 1.39285714]
Solution (x, y, z) in order =: [ 3.24038462 -0.25961538 -2.19230769]
